### ISSUE TITLE
Feature Request: Provide configuration support for ingress annotations

### ISSUE THREAD

**Issue by mcolomerc** [serverless/serverless-kubeless#114]
Provide configuration support for ingress rules.

```
provider:
  name: kubeless
  runtime: nodejs8

plugins:
  - serverless-kubeless

functions:
  capitalize:
    handler: handler.capitalize
    events:
      - http:
          path: /cap
```

Plugin defines nginx by default: https://github.com/serverless/serverless-kubeless/blob/master/lib/ingress.js 

` annotations: {
            'kubernetes.io/ingress.class': 'nginx',
            'nginx.ingress.kubernetes.io/rewrite-target': '/',
          },`

Aftrer function deployment, it's possible to re-configure the ingress rule to use traefik ingress.class:

` "annotations": {
      "kubernetes.io/ingress.class": "traefik",
      "traefik.frontend.rule.type": "PathPrefixStrip"
    }`

The we can invoke the function through traefik.  

`$ curl -H "Content-Type: application/json" -X POST -d 'xyz' http://localhost:31907/cap`

`Xyz`

Could be possible to add annotations to the configuration?

Thanks!
