### ISSUE TITLE
[WIP] Nodejs provider-level environment variables aren't propagated

### ISSUE THREAD

**Issue by ianserlin** [serverless/serverless-kubeless#123]
WIP while I work to fix the issue, but noting it here in case it's already in-progress somewhere else.

Version: `serverless-kubeless` version `0.4.2`.

Expected: environment variables specified at either the provider or function level are available to the deployed function at runtime.

Actual: only environment variables specified at the function level are available to the deployed function at runtime.

For example...

`TEST_FUNCTION_VARIABLE` will be available to the deployed function at runtime.
`TEST_PROVIDER_VARIABLE` will not be available to the deployed function at runtime.

```
service: gql

plugins:
  - serverless-kubeless

provider:
  name: kubeless
  runtime: nodejs8
  environment:
    TEST_PROVIDER_VARIABLE: "bluto"

functions:
  example:
    handler: handlers.example
    timeout: 300
    events:
      - http:
          path: examepl
    environment:
      TEST_FUNCTION_VARIABLE: "popeye"
```
