### ISSUE TITLE
Unable to redeploy functions

### ISSUE THREAD

**Issue by AlexRex** [serverless/serverless-kubeless#124]
When deploying a function, the first time I can deploy it without any issues, but if I try to redeploy it, either with the command `sls deploy` or only deploying the function with `sls deploy -f ping`, I got an error coming from kubernetes: 

```
$ sls deploy -f ping
Serverless: Packaging function: ping...
Serverless: Excluding development dependencies...
Serverless: Redeploying ping...

  Error --------------------------------------------------

  Found errors while processing the given functions:
Error: Unable to update the function ping. Received:
  Code: 422
  Message: Function.kubeless.io "ping" is invalid: apiVersion: Invalid value: "Function": must be kubeless.io/v1beta1

     For debugging logs, run again after setting the "SLS_DEBUG=*" environment variable.

  Get Support --------------------------------------------
     Docs:          docs.serverless.com
     Bugs:          github.com/serverless/serverless/issues
     Issues:        forum.serverless.com

  Your Environment Information -----------------------------
     OS:                     darwin
     Node Version:           8.11.1
     Serverless Version:     1.27.3
```

The first time after deploying everything it works perfect, but afterwards I am getting this error. 

This is my `serverless.yml` file: 

```
service: pingpong
provider:
  name: kubeless
  runtime: nodejs8
  hostname: myhostname.io

plugins:
  - serverless-kubeless

functions:
  ping:
    handler: handler.ping
    events:
      - http:
          path: /ping
```

And this is the handler:

```
const _ = require('lodash');
const fetch = require('node-fetch');

const ping = (event, context) => {
  const { request, response } = event.extensions;
  _.assign(event.data, { date: new Date().toTimeString() });

  return fetch('http://pong:8080/pong', {
    method: 'GET'
  }).then(async (res) => {
    const resp = await res.json();
    return {
      msg: 'called from ping, and response from',
      resp
    }
  }); 
};

module.exports = {
  ping
};
```

I noticed that if I change the handler file and try to redeploy, then I don't get any error, even if I only change one space.
