### ISSUE TITLE
Error Deploying to AWS EKS

### ISSUE THREAD

**Issue by james-ingold** [serverless/serverless-kubeless#140]
Hello, 

I'm trying to deploy to AWS EKS. I've configured kubectl for my cluster in amazon. I'm getting the following error when running serverless deploy -v

Unable to find required information for authenticating against the cluster
Unable to find required information for authenticating against the cluster
/Users/jamesingold/Repos/juxly/perfcol-serverless/node_modules/serverless-kubeless/lib/config.js:58
      return JSON.parse(this.configMag.data[key]);
                                           ^
TypeError: Cannot read property 'runtime-images' of undefined
    at Config.get (/Users/jamesingold/Repos/juxly/perfcol-serverless/node_modules/serverless-kubeless/lib/config.js:58:44)
    at Object.getRuntimeDepfile (/Users/jamesingold/Repos/juxly/perfcol-serverless/node_modules/serverless-kubeless/lib/helpers.js:183:34)
    at ReadStream.s.on (/Users/jamesingold/Repos/juxly/perfcol-serverless/node_modules/serverless-kubeless/deploy/kubelessDeploy.js:103:39)
    at ReadStream.emit (events.js:187:15)

It looks like there is an authentication issue, even though I'm logged in through kubectl
{
  "kind": "Status",
  "apiVersion": "v1",
  "metadata": {
    
  },
  "status": "Failure",
  "message": "configmaps \"kubeless-config\" is forbidden: User \"system:anonymous\" cannot get configmaps in the namespace \"kubeless\"",
  "reason": "Forbidden",
  "details": {
    "name": "kubeless-config",
    "kind": "configmaps"
  },
  "code": 403
}

**Comment by rddefauw** [comment]
What was the resolution?

**Comment by japsu** [comment]
That's no solution.

The problem is likely that the way Kubeless talks to the Kubernetes Master API fails to take into account the custom authentication method required by EKS in `~/.kube/config`:

```
- name: arn:aws:eks:eu-west-1:XXXXX:cluster/CLUSTERNAME
  user:
    exec:
      apiVersion: client.authentication.k8s.io/v1alpha1
      args:
      - token
      - -i
      - CLUSTERNAME
      command: aws-iam-authenticator
```

Please reopen.
