### ISSUE TITLE
Q: Serverless HTTP Trigger - serverless info crashes

### ISSUE THREAD

**Issue by nea** [serverless/serverless-kubeless#141]
Hi

I created a trigger as explained via serverless.yml. A simple http trigger:

```
  weather:
    handler: handler.weather
    events:
      - http:
          path: /weather
```

When I call `kubectl get ing` I see it being created. Now, I wanted to call `serverless info` as mentioned here: https://serverless.com/framework/docs/providers/kubeless/guide/functions/#custom-hostname-and-path

The following error is displayed:

```
const path = _.find(rule.http.paths, p => p.backend.serviceName === f).path;
                                         ^
TypeError: Cannot read property 'http' of undefined
```

It is triggered by `node_modules\serverless-kubeless\lib\get-info.js:119:42`

Am I missing something? Any help is much appreciated.

Thanks a lot in advance
