### ISSUE TITLE
Is possible use serverless-kubeless with java ?

### ISSUE THREAD

**Issue by klebermagno** [serverless/serverless-kubeless#153]
Kubeless work with java.
I create a project with Serverless-kubeless with java

 ```
service: func

provider:
  name: kubeless
  runtime: java

plugins:
  - serverless-kubeless

functions:
  func:
    handler: com.example.FunctionApp

```
this error message:

```
Serverless: Packaging function: func...
Serverless: Excluding development dependencies...
Serverless: Redeploying func...
Serverless: Unable to find any running pod for func. Retrying...
Serverless: Unable to find any running pod for func. Retrying...
Serverless: Unable to find any running pod for func. Retrying...
Serverless: Unable to find any running pod for func. Retrying...
Serverless: Giving up, unable to retrieve the status of the func deployment.
```

Is possible use serverless-kubeless with java ?
