### ISSUE TITLE
URL path parameters are not honored

### ISSUE THREAD

**Issue by ewrogers** [serverless/serverless-kubeless#182]
I'm not sure if this is a bug or maybe a feature request, but I have seen some other projects using URL paths in their `serverless.yaml`.

For example:
```
functions:
  get-users:
    handler: handler.getUsers
    events:
      - http:
          method: GET
          path: "${self:custom.apiPrefix}/users"
  get-user-by-id:
    handler: handler.getUserById
    events:
      - http:
          method: GET
          path: "${self:custom.apiPrefix}/users/{id}"
          request:
            parameters:
              paths:
                id: true
```

However, it seems this is not used by the Kubeless platform. Both requests route to the `get-users` function.

Am I missing something, or are URL path parameters not supported? That is kind of a big deal for REST APIs, what are the current workarounds? I can't imagine no one has this problem...
