### ISSUE TITLE
Can't overwrite function name by using name option

### ISSUE THREAD

**Issue by cscetbon** [serverless/serverless-kubeless#210]
Using name option doesn't do anything 
```
functions:
  playground:
    handler: handler.playgroundHandler
    name: ${self:provider.stage}-${self:provider.namespace}-kubeless-playground
```
the function deployed is still named **playground** when it should be **prod-ns1-kubeless-playground**
