### ISSUE TITLE
kubeless-config not found 

### ISSUE THREAD

**Issue by hejkerooo** [serverless/serverless-kubeless#227]
When I run `sls deploy` with following config:

```
service: test-service

plugins:
  - serverless-bundle
  - serverless-kubeless
  - serverless-kubeless-offline

provider:
  name: kubeless
  runtime: nodejs12
  memorySize: 256M

functions:
  hello:
    handler: handler.main
    events:
      - http:
          method: get
          path: /hello
```

```
export async function main(event, context) {
  console.log("works")

  return {
    statusCode: 200,
    body: `{id: 1}`,
  };
}
```

I'm receiving error

```
    Response: {"kind":"Status","apiVersion":"v1","metadata":{},"status":"Failure","message":"configmaps \"kubeless-config\" not found","reason":"NotFound","details":{"name":"kubeless-config","kind":"configmaps"},"code":404}
```
