### ISSUE TITLE
Is it possible to specify get parameters in the http mapping

### ISSUE THREAD

**Issue by spam-n-eggs** [serverless/serverless-kubeless#232]
Serverless for AWS Lambdas allows this and I was wondering if this is something that can be done with Kubeless.  

serverless.yml: 
```yaml
functions:
  hello:
    handler: handler.hello
    events:
      - http
          path: /hello/{name}
```
handler.js
```javascript
function hello(name, event, context) {
    return `Hello ${name}`;
}
```
