### ISSUE TITLE
serverless-webpack support?

### ISSUE THREAD

**Issue by rohit-ravikoti** [serverless/serverless-kubeless#83]
Hi,
Is there a way to get this working with [serverless-webpack](https://github.com/serverless-heaven/serverless-webpack)? It would be nice to be able to use babel.

Here's a sample repo of my try at it: https://github.com/rohit-ravikoti/serverless-kubeless-typescript-example

It doesn't work because the `serverless-kubeless` doesn't pickup the `handler.js` outputted by `serverless-webpack`.

EDIT: Added link to my attempt

**Comment by andresmgot** [comment]
Kubeless 0.2.4 has now support for using Zip files instead of single files. We should now be able to upload the whole `.serverless/function.zip` file if it is less than 1MB. Would that work for you?

**Comment by rohit-ravikoti** [comment]
I think so, how would I be able to make that work?

**Comment by andresmgot** [comment]
It will require changes in the serverless plugin but you can use for the time being the native `kubeless` client. Once you have a valid zip file (it is usually generated under the `.serverless` folder) you can deploy it executing:
```
kubeless function deploy hello --from-file .serverless/hello.zip --dependencies ./package.json --runtime nodejs6 --handler handler.hello --trigger-http
```

Let me know if the above works for you, we can start working on adding that feature afterwards.

**Comment by rohit-ravikoti** [comment]
Hmm, I just tried this, but the pod stays stuck in the Initializing state.

**Comment by rohit-ravikoti** [comment]
As an alternative, I could try to build with Babel and output to a `build/` directory? And then change the serverless.yml function handlers to `build/handler.capitalize`. 

I do get a strange error when I try that though. It says that the pod could not be found and retires a few times before crashing.

**Comment by andresmgot** [comment]
When it is stuck in Initializing state, what does `kubectl describe pod <pod_name>` outputs?

Also, how do you generate and deploy the `build/` directory? Note that the handler doesn't support characters like `/`, the files should be in the root folder.

**Comment by skunkwerk** [comment]
My zip files for a Python app in my .serverless folder are > 10 MB.  What do I do?

**Comment by andresmgot** [comment]
@rohit-ravikoti I have been working on adapting this repository to the Zip feature. I am afraid to say that even using a Zip file `webpack` is not supported since the format of the `handler.js` outputted is not recognized in the runtime container.

@skunkwerk You can use the [exclude](https://serverless.com/framework/docs/providers/aws/guide/packaging/#exclude--include) syntax to strip down the size of your Zip and just include code files.

The PR for supporting this file is https://github.com/serverless/serverless-kubeless/pull/102

Sorry both for the late response

**Comment by raul-madrigal** [comment]
@andresmgot, @rohit-ravikoti  Any news on this request?
I'm running Kubeless version: v1.0.2, with the following yml configuration.

```yml
service: my-api

plugins:
  - serverless-dotenv-plugin
  - serverless-webpack
  - serverless-kubeless
  - serverless-kubeless-offline

custom:
  stage: ${opt:stage, self:provider.stage}

  # Load our webpack config
  webpack:
    webpackConfig: ./webpack.config.js
    includeModules: true
    packager: 'yarn'
    excludeFiles: tests/**/*.test.js

provider:
  name: kubeless
  runtime: nodejs8
  stage: dev

functions:
    create-message:
    handler: src/services/v1/message/index.create
    events:
      - http:
          path: api/v1/message/create
```

The `- serverless-kubeless-offline` works great and I can hit http://localhost/api/v1/message/create with `serverless offline start`, but when I deploy with `serverless deploy` the `serverless-kubeless` plugin outputs the following error:

```
Serverless: Invoke webpack:package
Serverless: Packaging service...
Serverless: Unable to find any running pod for create-message. Retrying...
Serverless: Unable to find any running pod for create-message. Retrying...
Serverless: Unable to find any running pod for create-message. Retrying...
Serverless: Unable to find any running pod for create-message. Retrying...
Serverless: Giving up, unable to retrieve the status of the create-message deployment. 
/Users/raulmadrigal/repos/my-api/backend/node_modules/bluebird/js/release/async.js:61
        fn = function () { throw arg; };
                           ^

Error: Unable to retrieve the status of the create-message deployment
    at module.exports.logError (/Users/raulmadrigal/.nvm/versions/node/v8.10.0/lib/node_modules/serverless/lib/classes/Error.js:92:11)
    at process.on (/Users/raulmadrigal/.nvm/versions/node/v8.10.0/lib/node_modules/serverless/bin/serverless:21:3)
    at emitTwo (events.js:126:13)
    at process.emit (events.js:214:7)
    at methodName (/Users/raulmadrigal/repos/my-api/backend/node_modules/bluebird/js/release/debuggability.js:199:33)
    at activeFireEvent (/Users/raulmadrigal/repos/my-api/backend/node_modules/bluebird/js/release/debuggability.js:242:44)
    at fireRejectionEvent (/Users/raulmadrigal/repos/my-api/backend/node_modules/bluebird/js/release/debuggability.js:632:14)
    at Promise._notifyUnhandledRejection (/Users/raulmadrigal/repos/my-api/backend/node_modules/bluebird/js/release/debuggability.js:65:9)
    at Timeout._onTimeout (/Users/raulmadrigal/repos/my-api/backend/node_modules/bluebird/js/release/debuggability.js:44:14)
    at ontimeout (timers.js:482:11)
    at tryOnTimeout (timers.js:317:5)
    at Timer.listOnTimeout (timers.js:277:5)
```
